apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-cm
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: coredns
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  Corefile: {{ print "|-" }}
    {{- range $name, $conf := .Values.coredns.extraConfig }}
    {{ $name }}{{ if $conf.parameters }} {{ $conf.parameters }}{{ end }}
    {{- end }}
    {{ range .Values.coredns.servers }}
    {{- range $idx, $zone := .zones }}{{ if $idx }} {{ else }}{{ end }}{{ default "" $zone.scheme }}{{ default "." $zone.zone }}{{ else }}.{{ end -}}
    {{- if .port }}{{ print ":"}}{{ .port }} {{ end -}}
    {{ print "{"}}
      {{- range .plugins }}
        {{ .name }}{{ if .parameters }} {{ include "common.tplvalues.render" (dict "value" .parameters "context" $) }}{{ end }}{{ if .configBlock }} {{ print "{"}}
{{ include "common.tplvalues.render" (dict "value" .configBlock "context" $) | indent 12 }}
        }{{ end }}
      {{- end }}
    }
    {{ end }}
  {{- range .Values.coredns.zoneFiles }}
  {{ .filename }}: |
{{ include "common.tplvalues.render" (dict "value" .contents "context" $) | indent 4 }}
  {{- end }}