apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-cm
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: etcd
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  etcd.config.yml: | 
    {{- include "common.tplvalues.render" (dict "value" .Values.etcd.configFile "context" $) | nindent 4 -}}