annotations:
  # CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE
  # https://github.com/bitnami/charts/blob/main/CHART_CATEGORIES
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: v1.17.0
dependencies:
  - name: common
    repository: file://../common
    version: 2.x.x
description: Prometheus exporter for podman environments exposing containers, pods, images, volumes and networks information.
home: https://github.com/fsdrw08/helm-charts
icon: https://bitnami.com/assets/stacks/prometheus-podman-exporter/img/prometheus-podman-exporter-stack-220x234.png
keywords:
  - monitoring
  - observability
  - podman kube play
maintainers:
  - name: Windom WU
    url: https://github.com/fsdrw08/helm-charts
name: prometheus-podman-exporter
sources:
  - https://github.com/containers/prometheus-podman-exporter/
  - ...
version: 0.1.0
