## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

## @section Common parameters
##
## @param nameOverride String to partially override common.names.name
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}

## @param exporter.workloadKind specify the deploy kind： Pod, or Deployment
workloadKind: Pod
## @section prometheus-podman-exporter Parameters
##

## %%MAIN_CONTAINER/POD_DESCRIPTION%%
##
exporter:
  ## prometheus-podman-exporter image
  ## ref: https://quay.io/repository/navidys/prometheus-podman-exporter?tab=tags
  ## @param exporter.image.registry prometheus-podman-exporter image registry
  ## @param exporter.image.repository prometheus-podman-exporter image repository
  ## @param exporter.image.tag prometheus-podman-exporter image tag (immutable tags are recommended)
  ## @param exporter.image.digest prometheus-podman-exporter image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag image tag (immutable tags are recommended)
  ## @param exporter.image.pullPolicy prometheus-podman-exporter image pull policy
  ## @param exporter.image.pullSecrets prometheus-podman-exporter image pull secrets
  ##
  image:
    registry: quay.io
    repository: navidys/prometheus-podman-exporter
    tag: v1.18.0
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
  ## @param exporter.podRestartPolicy specify the pod restart policy if workloadKind set to Pod
  ## available options: Always, OnFailure, Never
  podRestartPolicy: Never
  ## @param exporter.replicaCount Number of prometheus-podman-exporter replicas to deploy
  ##
  replicaCount: 1
  ## @param exporter.containerPorts prometheus-podman-exporter container port to expose to host
  ## e.g.
  ## containerPorts:
  ##   - name: http
  ##     containerPort: 80
  ##     hostPort: 80
  ##     hostIP: 192.168.255.10
  ##     protocol: TCP
  ##   - name: https
  ##     containerPort: 443
  ##     hostPort: 443
  ##     hostIP: 192.168.255.10
  ##     protocol: TCP
  ##
  containerPorts: {}
  ## Configure extra options for prometheus-podman-exporter containers' liveness and readiness probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
  ## @param exporter.livenessProbe.enabled Enable livenessProbe on prometheus-podman-exporter containers
  ## @param exporter.livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  ## @param exporter.livenessProbe.periodSeconds Period seconds for livenessProbe
  ## @param exporter.livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  ## @param exporter.livenessProbe.failureThreshold Failure threshold for livenessProbe
  ## @param exporter.livenessProbe.successThreshold Success threshold for livenessProbe
  ##
  livenessProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param exporter.readinessProbe.enabled Enable readinessProbe on prometheus-podman-exporter containers
  ## @param exporter.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  ## @param exporter.readinessProbe.periodSeconds Period seconds for readinessProbe
  ## @param exporter.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  ## @param exporter.readinessProbe.failureThreshold Failure threshold for readinessProbe
  ## @param exporter.readinessProbe.successThreshold Success threshold for readinessProbe
  ## note: podman not support readinessProbe currently
  ##
  readinessProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param exporter.startupProbe.enabled Enable startupProbe on prometheus-podman-exporter containers
  ## @param exporter.startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
  ## @param exporter.startupProbe.periodSeconds Period seconds for startupProbe
  ## @param exporter.startupProbe.timeoutSeconds Timeout seconds for startupProbe
  ## @param exporter.startupProbe.failureThreshold Failure threshold for startupProbe
  ## @param exporter.startupProbe.successThreshold Success threshold for startupProbe
  ##
  startupProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param exporter.customLivenessProbe Custom livenessProbe that overrides the default one
  ##
  customLivenessProbe: {}
  ## @param exporter.customReadinessProbe Custom readinessProbe that overrides the default one
  ##
  customReadinessProbe: {}
  ## @param exporter.customStartupProbe Custom startupProbe that overrides the default one
  ##
  customStartupProbe: {}
  ## prometheus-podman-exporter resource requests and limits
  ## ref: http://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  ## @param exporter.resourcesPreset Set prometheus-podman-exporter container resources according to one common preset (allowed values: none, nano, small, medium, large, xlarge, 2xlarge). This is ignored if exporter.resources is set (exporter.resources is recommended for production).
  ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  ##
  resourcesPreset: "small"
  ## @param exporter.resources Set prometheus-podman-exporter container requests and limits for different resources like CPU or memory (essential for production workloads)
  ## Example:
  ## resources:
  ##   requests:
  ##     cpu: 2
  ##     memory: 512Mi
  ##   limits:
  ##     cpu: 3
  ##     memory: 1024Mi
  ##
  resources: {}
  ## Configure Pods Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  ## @param exporter.podSecurityContext.enabled Enabled prometheus-podman-exporter pods' Security Context
  ## @param exporter.podSecurityContext.fsGroup Set prometheus-podman-exporter pod's Security Context fsGroup
  ## note: podman kube play does not support fsGroup yet
  ##
  podSecurityContext:
    enabled: false
    # fsGroup: 1001
  ## Configure Container Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param exporter.containerSecurityContext.enabled Enabled prometheus-podman-exporter containers' Security Context
  ## @param exporter.containerSecurityContext.runAsUser Set prometheus-podman-exporter containers' Security Context runAsUser
  ## @param exporter.containerSecurityContext.runAsNonRoot Set prometheus-podman-exporter containers' Security Context runAsNonRoot
  ## @param exporter.containerSecurityContext.readOnlyRootFilesystem Set prometheus-podman-exporter containers' Security Context runAsNonRoot
  ##
  containerSecurityContext:
    enabled: true
    runAsUser: 65534
    seLinuxOptions:
      type: spc_t

  # %%OTHER_PARAMETERS_RELATED_TO_THIS_CONTAINER/POD%%
  configFile:
    ## @param exporter.configFile.web content of web config file
    web: {}
  ## @param exporter.existingConfigmap The name of an existing ConfigMap with your custom configuration for %%MAIN_CONTAINER_NAME%%
  ##
  ## @param exporter.tls secret setting of cert and key or whatever tls content will set in the container
  ##
  tls:
    ## @param exporter.tls.mountPath secret mount path (dir) setting of cert and key or whatever tls content will set in the container
    ## this config should match with config under grafana.configFile.server.cert_key and grafana.configFile.server.cert_file if any
    ##
    mountPath: /etc/prometheus/certs
    ## @param exporter.tls.contents secret content of cert and key or whatever tls content will set in the container
    ## You can set the content key as whatever file name you like
    ## But the tls set in configFiles above must match with the settings here
    ## key and certificate should start with -----BEGIN CERTIFICATE----- or -----BEGIN RSA PRIVATE KEY-----
    ## e.g.
    ## contents:
    ##  ca.crt: ""
    ##  exporter.crt: ""
    ##  exporter.key: ""
    ##
    contents: {}
  ## @param exporter.existingConfigmap The name of an existing ConfigMap with your custom configuration for prometheus-podman-exporter
  ##
  existingConfigmap:
  ## @param exporter.command Override default container command (useful when using custom images)
  ##
  command: []
  ## @param exporter.flags flags to launch prometheus-podman-exporter
  flags:
    collector:
      ## @param exporter.flags.collector.cache_duration Duration (seconds) to retrieve container, size and refresh the cache. (default 3600)
      ##
      cache_duration: 3600
      ## @param exporter.flags.collector.enable-all Enable all collectors by default.
      ##
      enable-all: true
      ## @param exporter.flags.collector.enhance-metrics enhance all metrics with the same field as for their podman_<...>_info metrics.
      ##
      enhance-metrics: true
      ## @param exporter.flags.collector.image Enable image collector.
      ##
      image: false
      ## @param exporter.flags.collector.network Enable network collector.
      ##
      network: false
      ## @param exporter.flags.collector.pod Enable pod collector.
      ##
      pod: false
      ## @param exporter.flags.collector.store_labels Convert pod/container/image labels on prometheus metrics for each pod/container/image.
      ##
      store_labels: false
      ## @param exporter.flags.collector.system Enable system collector.
      ##
      system: false
      ## @param exporter.flags.collector.volume Enable volume collector.
      ##
      volume: false
      ## @param exporter.flags.collector.whitelisted_labels Comma separated list of pod/container/image labels to be converted to labels on prometheus metrics for each pod/container/image.
      ## collector.store_labels must be set to false for this to take effect.
      ##
      whitelisted_labels: false
    ## @param exporter.flags.debug Set log level to debug.
    debug: false
    web:
      config:
        ## @param exporter.flags.web.config.file [EXPERIMENTAL] Path to configuration file that can enable TLS or authentication.
        file: # /etc/exporter/web.yaml
      ## @param exporter.flags.web.Exclude metrics about the exporter itself (promhttp_*, process_*, go_*).
      disable-exporter-metrics: false
      ## @param exporter.flags.web.Address on which to expose metrics and web interface. (default ":9882")
      listen-address: :9882
      ## @param exporter.flags.web.Maximum number of parallel scrape requests. Use 0 to disable (default 40)
      max-requests: 40
      ## @param exporter.flags.web.Path under which to expose metrics. (default "/metrics")
      telemetry-path: /metrics
  ## @param exporter.args Override default container args (useful when using custom images)
  ##
  args: []
  ## @param exporter.hostAliases prometheus-podman-exporter pods host aliases
  ## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
  ##
  hostAliases: []
  ## @param exporter.podLabels Extra labels for prometheus-podman-exporter pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  ##
  podLabels: {}
  ## @param exporter.podAnnotations Annotations for prometheus-podman-exporter pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations:
    io.podman.annotations.userns: keep-id:uid=65534,gid=65534
  ## Autoscaling configuration
  ## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  ## @param exporter.autoscaling.enabled Enable autoscaling for exporter
  ## @param exporter.autoscaling.minReplicas Minimum number of exporter replicas
  ## @param exporter.autoscaling.maxReplicas Maximum number of exporter replicas
  ## @param exporter.autoscaling.targetCPU Target CPU utilization percentage
  ## @param exporter.autoscaling.targetMemory Target Memory utilization percentage
  ##
  autoscaling:
    enabled: false
    minReplicas: ""
    maxReplicas: ""
    targetCPU: ""
    targetMemory: ""

  ## @param exporter.extraEnvVars Array with extra environment variables to add to prometheus-podman-exporter nodes
  ## e.g:
  ## extraEnvVars:
  ##   - name: FOO
  ##     value: "bar"
  ##
  extraEnvVars: []
  ## @param exporter.extraEnvVarsCM Name of existing ConfigMap containing extra env vars for prometheus-podman-exporter nodes
  ##
  extraEnvVarsCM: ""
  ## @param exporter.extraEnvVarsSecret Name of existing Secret containing extra env vars for prometheus-podman-exporter nodes
  ##
  extraEnvVarsSecret: ""
  ## @param exporter.extraVolumes Optionally specify extra list of additional volumes for the prometheus-podman-exporter pod(s)
  ##
  extraVolumes: []
  ## @param exporter.extraVolumeMounts Optionally specify extra list of additional volumeMounts for the prometheus-podman-exporter container(s)
  ##
  extraVolumeMounts: []
  ## @param exporter.sidecars Add additional sidecar containers to the prometheus-podman-exporter pod(s)
  ## e.g:
  ## sidecars:
  ##   - name: your-image-name
  ##     image: your-image
  ##     imagePullPolicy: Always
  ##     ports:
  ##       - name: portname
  ##         containerPort: 1234
  ##
  sidecars: []
  ## @param exporter.initContainers Add additional init containers to the prometheus-podman-exporter pod(s)
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
  ## e.g:
  ## initContainers:
  ##  - name: your-image-name
  ##    image: your-image
  ##    imagePullPolicy: Always
  ##    command: ['sh', '-c', 'echo "hello world"']
  ##
  initContainers: []

## @section Persistence Parameters
##

## Enable persistence using Persistent Volume Claims
## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## @param persistence.enabled Enable persistence using Persistent Volume Claims
  ##
  enabled: false
  ## @param persistence.mountPath Path to mount the volume at.
  ##
  mountPath: /bitnami/exporter/data
  ## @param persistence.subPath The subdirectory of the volume to mount to, useful in dev environments and one PV for multiple services
  ##
  subPath: ""
  ## @param persistence.storageClass Storage class of backing PVC
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: ""
  ## @param persistence.annotations Persistent Volume Claim annotations
  ##
  annotations: {}
  ## @param persistence.accessModes Persistent Volume Access Modes
  ##
  accessModes:
    - ReadWriteOnce
  ## @param persistence.size Size of data volume
  ##
  size: 8Gi
  ## @param persistence.existingClaim The name of an existing PVC to use for persistence
  ##
  existingClaim: ""
## @section Init Container Parameters
##

## 'volumePermissions' init container parameters
## Changes the owner and group of the persistent volume mount point to runAsUser:fsGroup values
##   based on the *podSecurityContext/*containerSecurityContext parameters
##
volumePermissions:
  ## @param volumePermissions.enabled Enable init container that changes the owner/group of the PV mount point to `runAsUser:fsGroup`
  ##
  enabled: false
  ## OS Shell + Utility image
  ## ref: https://hub.docker.com/r/bitnami/os-shell/tags/
  ## @param volumePermissions.image.registry OS Shell + Utility image registry
  ## @param volumePermissions.image.repository OS Shell + Utility image repository
  ## @param volumePermissions.image.tag OS Shell + Utility image tag (immutable tags are recommended)
  ## @param volumePermissions.image.pullPolicy OS Shell + Utility image pull policy
  ## @param volumePermissions.image.pullSecrets OS Shell + Utility image pull secrets
  ##
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: 11-debian-11-r%%IMAGE_REVISION%%
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
  ## Init container's resource requests and limits
  ## ref: http://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  ## @param volumePermissions.resourcesPreset Set init container resources according to one common preset (allowed values: none, nano, small, medium, large, xlarge, 2xlarge). This is ignored if volumePermissions.resources is set (volumePermissions.resources is recommended for production).
  ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  ##
  resourcesPreset: "nano"
  ## @param volumePermissions.resources Set init container requests and limits for different resources like CPU or memory (essential for production workloads)
  ## Example:
  ## resources:
  ##   requests:
  ##     cpu: 2
  ##     memory: 512Mi
  ##   limits:
  ##     cpu: 3
  ##     memory: 1024Mi
  ##
  resources: {}
  ## Init container Container Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param volumePermissions.containerSecurityContext.runAsUser Set init container's Security Context runAsUser
  ## NOTE: when runAsUser is set to special value "auto", init container will try to chown the
  ##   data folder to auto-determined user&group, using commands: `id -u`:`id -G | cut -d" " -f2`
  ##   "auto" is especially useful for OpenShift which has scc with dynamic user ids (and 0 is not allowed)
  ##
  containerSecurityContext:
    runAsUser: 0

## @section Other Parameters
##

## %%SUBCHART_CONTAINER/POD_DESCRIPTION%%
##
# %%SUBCHART_NAME%%:
SUBCHART_NAME:
  enabled: false
  # %%OTHER_PARAMETERS_RELATED_TO_THIS_SUBCHART%%
