{{- if and .Values.cockpit.tls.contents -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-sec-tls
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: cockpit
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- range $key, $val := .Values.cockpit.tls.contents }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
