{{- if .Values.389ds.DS_DM_PASSWORD }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "389ds.fullname" . }}
  labels:
    {{- include "389ds.labels" . | nindent 4 }}
type: Opaque
data:
  DS_DM_PASSWORD: {{ .Values.389ds.DS_DM_PASSWORD }}
{{- end }}