## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

## @section Common parameters
##
## @param nameOverride String to partially override common.names.name
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param namespaceOverride String to fully override common.names.namespace
##
namespaceOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}

## @param instanceKind specify the deploy kind： Pod, or Deployment
instanceKind: Pod

## @section drone Parameters
##

## %%MAIN_CONTAINER/POD_DESCRIPTION%%
##
droneRunnerDocker:
  ## drone-runner-docker image
  ## ref: https://hub.docker.com/r/drone/drone/tags
  ## @param droneRunnerDocker.image.registry drone image registry
  ## @param droneRunnerDocker.image.repository drone image repository
  ## @param droneRunnerDocker.image.tag drone image tag (immutable tags are recommended)
  ## @param droneRunnerDocker.image.digest drone image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag image tag (immutable tags are recommended)
  ## @param droneRunnerDocker.image.pullPolicy drone image pull policy
  ## @param droneRunnerDocker.image.pullSecrets drone image pull secrets
  ##
  image:
    registry: docker.io
    repository: drone/drone-runner-docker
    tag: 1.8.3
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
  ## @param droneRunnerDocker.podRestartPolicy specify the pod restart policy if instanceKind set to Pod
  ## available options: Always, OnFailure, Never
  podRestartPolicy: Never
  ## @param droneRunnerDocker.replicaCount Number of %%SECONDARY_CONTAINER%% replicas to deploy
  ##
  replicaCount: 1
  ## @param droneRunnerDocker.containerPorts %%SECONDARY_CONTAINER%% container port to expose to host
  ## containerPorts:
  ##   - name: http
  ##     containerPort: 80
  ##     hostIP: 192.168.255.10
  ##     protocol: TCP
  ##   - name: https
  ##     containerPort: 443
  ##     hostIP: 192.168.255.10
  ##     protocol: TCP
  ##
  containerPorts: {}
  ## Configure extra options for %%SECONDARY_CONTAINER%% containers' liveness and readiness probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
  ## @param droneRunnerDocker.livenessProbe.enabled Enable livenessProbe on %%SECONDARY_CONTAINER%% containers
  ## @param droneRunnerDocker.livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  ## @param droneRunnerDocker.livenessProbe.periodSeconds Period seconds for livenessProbe
  ## @param droneRunnerDocker.livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  ## @param droneRunnerDocker.livenessProbe.failureThreshold Failure threshold for livenessProbe
  ## @param droneRunnerDocker.livenessProbe.successThreshold Success threshold for livenessProbe
  ##
  livenessProbe:
    enabled: false
    initialDelaySeconds: 60
    periodSeconds: 300
    timeoutSeconds: 10
    failureThreshold: 5
    successThreshold: 1
    httpGet:
      path: /healthz
      port: http
  ## @param droneRunnerDocker.readinessProbe.enabled Enable readinessProbe on %%SECONDARY_CONTAINER%% containers
  ## @param droneRunnerDocker.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  ## @param droneRunnerDocker.readinessProbe.periodSeconds Period seconds for readinessProbe
  ## @param droneRunnerDocker.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  ## @param droneRunnerDocker.readinessProbe.failureThreshold Failure threshold for readinessProbe
  ## @param droneRunnerDocker.readinessProbe.successThreshold Success threshold for readinessProbe
  ##
  readinessProbe:
    enabled: false
    initialDelaySeconds: 60
    periodSeconds: 300
    timeoutSeconds: 10
    failureThreshold: 5
    successThreshold: 1
    httpGet:
      path: /healthz
      port: http
  ## @param droneRunnerDocker.startupProbe.enabled Enable startupProbe on %%SECONDARY_CONTAINER%% containers
  ## @param droneRunnerDocker.startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
  ## @param droneRunnerDocker.startupProbe.periodSeconds Period seconds for startupProbe
  ## @param droneRunnerDocker.startupProbe.timeoutSeconds Timeout seconds for startupProbe
  ## @param droneRunnerDocker.startupProbe.failureThreshold Failure threshold for startupProbe
  ## @param droneRunnerDocker.startupProbe.successThreshold Success threshold for startupProbe
  ##
  startupProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param droneRunnerDocker.customLivenessProbe Custom livenessProbe that overrides the default one
  ##
  customLivenessProbe: {}
  ## @param droneRunnerDocker.customReadinessProbe Custom readinessProbe that overrides the default one
  ##
  customReadinessProbe: {}
  ## @param droneRunnerDocker.customStartupProbe Custom startupProbe that overrides the default one
  ##
  customStartupProbe: {}
  ## %%SECONDARY_CONTAINER%% resource requests and limits
  ## ref: http://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  ## @param droneRunnerDocker.resourcesPreset Set %%MAIN_CONTAINER_NAME%% container resources according to one common preset (allowed values: none, nano, small, medium, large, xlarge, 2xlarge). This is ignored if %%MAIN_OBJECT_BLOCK%%.resources is set (%%MAIN_OBJECT_BLOCK%%.resources is recommended for production).
  ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  ##
  resourcesPreset: "nano"
  ## @param droneRunnerDocker.resources.limits The resources limits for the %%SECONDARY_CONTAINER%% containers
  ## @param droneRunnerDocker.resources.requests The requested resources for the %%SECONDARY_CONTAINER%% containers
  ##
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests: {}
  ## Configure Pods Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  ## @param droneRunnerDocker.podSecurityContext.enabled Enabled %%SECONDARY_CONTAINER%% pods' Security Context
  ## @param droneRunnerDocker.podSecurityContext.fsGroup Set %%SECONDARY_CONTAINER%% pod's Security Context fsGroup
  ##
  podSecurityContext:
    enabled: false
    fsGroup: 1001
  ## Configure Container Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param droneRunnerDocker.containerSecurityContext.enabled Enabled %%SECONDARY_CONTAINER%% containers' Security Context
  ## @param droneRunnerDocker.containerSecurityContext.runAsUser Set %%SECONDARY_CONTAINER%% containers' Security Context runAsUser
  ## @param droneRunnerDocker.containerSecurityContext.runAsNonRoot Set %%SECONDARY_CONTAINER%% containers' Security Context runAsNonRoot
  ## @param droneRunnerDocker.containerSecurityContext.readOnlyRootFilesystem Set %%SECONDARY_CONTAINER%% containers' Security Context runAsNonRoot
  ##
  containerSecurityContext:
    enabled: false
    runAsUser: 1001
    runAsNonRoot: true
    readOnlyRootFilesystem: false

  # %%OTHER_PARAMETERS_RELATED_TO_THIS_CONTAINER/POD%%

  ## @param droneRunnerDocker.podmanSocketDir podman socket mount to drone runner docker container path: /var/run/docker.sock
  ##
  podmanSocketDir: /run/user/1000/podman/
  ## @param droneRunnerDocker.podmanSocket podman socket mount to drone runner docker container path: /var/run/docker.sock
  ##
  podmanSocket: /run/user/1000/podman/podman.sock
  ## @param droneRunnerDocker.existingConfigmap The name of an existing ConfigMap with your custom configuration for %%SECONDARY_CONTAINER%%
  ##
  existingConfigmap:
  ## @param droneRunnerDocker.command Override default container command (useful when using custom images)
  ##
  command: []
  ## @param droneRunnerDocker.args Override default container args (useful when using custom images)
  ##
  args: []
  ## @param droneRunnerDocker.hostAliases %%SECONDARY_CONTAINER%% pods host aliases
  ## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
  ##
  hostAliases: []
  ## @param droneRunnerDocker.podLabels Extra labels for %%SECONDARY_CONTAINER%% pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  ##
  podLabels: {}
  ## @param droneRunnerDocker.podAnnotations Annotations for %%SECONDARY_CONTAINER%% pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations: {}
  ## Autoscaling configuration
  ## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  ## @param droneRunnerDocker.autoscaling.enabled Enable autoscaling for droneRunnerDocker
  ## @param droneRunnerDocker.autoscaling.minReplicas Minimum number of droneRunnerDocker replicas
  ## @param droneRunnerDocker.autoscaling.maxReplicas Maximum number of droneRunnerDocker replicas
  ## @param droneRunnerDocker.autoscaling.targetCPU Target CPU utilization percentage
  ## @param droneRunnerDocker.autoscaling.targetMemory Target Memory utilization percentage
  ##
  autoscaling:
    enabled: false
    minReplicas: ""
    maxReplicas: ""
    targetCPU: ""
    targetMemory: ""
  ## @param droneRunnerDocker.extraEnvVars
  ## e.g:
  ## extraEnvVars:
  ##   - name: FOO
  ##     value: "bar"
  ##
  extraEnvVars:
    ## see more env vars in https://docs.drone.io/runner/docker/configuration/reference/

    ## @param droneRunnerDocker.extraEnvVars.DRONE_RUNNER_CAPACITY
    ## Optional number value. Limits the number of concurrent pipelines that a runner can execute. The runner executes 2 concurrent pipelines by default.
    ## Ref: https://docs.drone.io/runner/docker/configuration/reference/drone-runner-capacity/
    ##
    - name: DRONE_RUNNER_CAPACITY
      value: 2
    ## @param droneRunnerDocker.extraEnvVars.DRONE_RUNNER_NAME
    ## Optional string value. Sets the name of the runner. The runner name is stored in the server and can be used to trace a build back to a specific runner.
    ## Ref: https://docs.drone.io/runner/docker/configuration/reference/drone-runner-name/
    - name: DRONE_RUNNER_NAME
      value: podman_runner
    ## @param droneRunnerDocker.extraEnvVars.DRONE_RPC_SKIP_VERIFY
    ## Optional string value. Sets the name of the runner. The runner name is stored in the server and can be used to trace a build back to a specific runner.
    ## Ref: https://docs.drone.io/runner/docker/configuration/reference/drone-runner-name/
    - name: DRONE_RPC_SKIP_VERIFY
      value: false

  ## @param droneRunnerDocker.extraEnvVarsInSecret
  extraEnvVarsInSecret:
    ## @param droneRunnerDocker.extraEnvVarsInSecret.DRONE_RPC_HOST
    ## REQUIRED: Set the user-visible Drone hostname, sans protocol.
    ## Ref: https://docs.drone.io/installation/reference/drone-server-host/
    ##
    DRONE_RPC_HOST:
    ## @param droneRunnerDocker.extraEnvVarsInSecret.DRONE_RPC_PROTO
    ## The protocol to pair with the value in DRONE_SERVER_HOST (http or https).
    ## Ref: https://docs.drone.io/installation/reference/drone-server-proto/
    ##
    DRONE_RPC_PROTO: https
    ## @param droneRunnerDocker.extraEnvVarsInSecret.DRONE_RPC_SECRET
    ## REQUIRED: Set the secret secret token that the Drone server and its Runners will use
    ## to authenticate. This is commented out in order to leave you the ability to set the
    ## key via a separately provisioned secret (see existingSecretName above).
    ## Ref: https://docs.drone.io/installation/reference/drone-rpc-secret/
    ##
    DRONE_RPC_SECRET: secret
  ## @param droneRunnerDocker.extraEnvVarsCM Name of existing ConfigMap containing extra env vars for %%MAIN_CONTAINER_NAME%% nodes
  ##
  extraEnvVarsCM: ""
  ## @param droneRunnerDocker.extraEnvVarsSecret Name of existing Secret containing extra env vars for %%MAIN_CONTAINER_NAME%% nodes
  ##
  extraEnvVarsSecret: ""
  ## @param droneRunnerDocker.extraVolumes Optionally specify extra list of additional volumes for the %%MAIN_CONTAINER_NAME%% pod(s)
  ##
  extraVolumes: []
  ## @param droneRunnerDocker.extraVolumeMounts Optionally specify extra list of additional volumeMounts for the %%MAIN_CONTAINER_NAME%% container(s)
  ##
  extraVolumeMounts: []
  ## @param droneRunnerDocker.sidecars Add additional sidecar containers to the %%MAIN_CONTAINER_NAME%% pod(s)
  ## e.g:
  ## sidecars:
  ##   - name: your-image-name
  ##     image: your-image
  ##     imagePullPolicy: Always
  ##     ports:
  ##       - name: portname
  ##         containerPort: 1234
  ##
  sidecars: []
  ## @param droneRunnerDocker.initContainers Add additional init containers to the %%MAIN_CONTAINER_NAME%% pod(s)
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
  ## e.g:
  ## initContainers:
  ##  - name: your-image-name
  ##    image: your-image
  ##    imagePullPolicy: Always
  ##    command: ['sh', '-c', 'echo "hello world"']
  ##
  initContainers: []

## %%SECONDARY_CONTAINER/POD_DESCRIPTION%%
##

## @section Persistence Parameters
##

## Enable persistence using Persistent Volume Claims
## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## @param persistence.enabled Enable persistence using Persistent Volume Claims
  ##
  enabled: false
  ## @param persistence.mountPath Path to mount the volume at.
  ##
  mountPath:
  ## @param persistence.subPath The subdirectory of the volume to mount to, useful in dev environments and one PV for multiple services
  ##
  subPath: ""
  ## @param persistence.storageClass Storage class of backing PVC
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: ""
  ## @param persistence.annotations Persistent Volume Claim annotations
  ##
  annotations: {}
  ## @param persistence.accessModes Persistent Volume Access Modes
  ##
  accessModes:
    - ReadWriteOnce
  ## @param persistence.size Size of data volume
  ##
  size: 8Gi
  ## @param persistence.existingClaim The name of an existing PVC to use for persistence
  ##
  existingClaim: ""
  ## @param persistence.dataSource Custom PVC data source
  ##
  dataSource: {}
## @section Init Container Parameters
##

## 'volumePermissions' init container parameters
## Changes the owner and group of the persistent volume mount point to runAsUser:fsGroup values
##   based on the *podSecurityContext/*containerSecurityContext parameters
##
volumePermissions:
  ## @param volumePermissions.enabled Enable init container that changes the owner/group of the PV mount point to `runAsUser:fsGroup`
  ##
  enabled: false
  ## OS Shell + Utility image
  ## ref: https://hub.docker.com/r/bitnami/os-shell/tags/
  ## @param volumePermissions.image.registry OS Shell + Utility image registry
  ## @param volumePermissions.image.repository OS Shell + Utility image repository
  ## @param volumePermissions.image.tag OS Shell + Utility image tag (immutable tags are recommended)
  ## @param volumePermissions.image.pullPolicy OS Shell + Utility image pull policy
  ## @param volumePermissions.image.pullSecrets OS Shell + Utility image pull secrets
  ##
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: 11-debian-11-r # %%IMAGE_REVISION%%
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
  ## Init container's resource requests and limits
  ## ref: http://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  ## @param volumePermissions.resourcesPreset Set init container resources according to one common preset (allowed values: none, nano, small, medium, large, xlarge, 2xlarge). This is ignored if volumePermissions.resources is set (volumePermissions.resources is recommended for production).
  ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  ##
  resourcesPreset: "nano"
  ## @param volumePermissions.resources.limits The resources limits for the init container
  ## @param volumePermissions.resources.requests The requested resources for the init container
  ## e.g.
  ## resources:
  ##   limits:
  ##     cpu: 100m
  ##     memory: 128Mi
  ##   requests:
  ##     cpu: 100m
  ##     memory: 128Mi
  resources:
    limits: {}
    requests: {}
  ## Init container Container Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param volumePermissions.containerSecurityContext.runAsUser Set init container's Security Context runAsUser
  ## NOTE: when runAsUser is set to special value "auto", init container will try to chown the
  ##   data folder to auto-determined user&group, using commands: `id -u`:`id -G | cut -d" " -f2`
  ##   "auto" is especially useful for OpenShift which has scc with dynamic user ids (and 0 is not allowed)
  ##
  containerSecurityContext:
    runAsUser: 0

## @section Other Parameters
##

## %%SUBCHART_CONTAINER/POD_DESCRIPTION%%
##
# %%SUBCHART_NAME%%:
SUBCHART_NAME:
  enabled: false
  # %%OTHER_PARAMETERS_RELATED_TO_THIS_SUBCHART%%
