annotations:
  # CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE
  # https://github.com/bitnami/charts/blob/main/CHART_CATEGORIES
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
# https://github.com/jenkinsci/docker/releases
# https://hub.docker.com/r/jenkins/jenkins/tags?page=1
appVersion: "2.414.1-lts"
dependencies:
  - name: common
    repository: file://../common
    version: 2.x.x
description: Jenkins server helm chart for podman kube play
home: https://github.com/fsdrw08/helm-charts
icon: https://camo.githubusercontent.com/a5004ae5bffb9a59384514fd88d3f18c47e1e0373bfda94a18b422e4a164d399/68747470733a2f2f6a656e6b696e732e696f2f73697465732f64656661756c742f66696c65732f6a656e6b696e735f6c6f676f2e706e67

keywords:
  - podman kube play
  - Jenkins
  - ci
  - cd
maintainers:
  - name: Windom WU
    url: https://github.com/fsdrw08/helm-charts
name: jenkins
sources:
  - https://github.com/fsdrw08/helm-charts/tree/main/charts/jenkins-server
version: 0.1.0
