{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-cm
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: redis
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
{{- $unsorted := .Values.redis.configFiles | toJson | fromJson -}}
{{- range $key, $val := $unsorted }}
  {{ $key }}.conf: |-
{{- range $setting, $value := $val }}
  {{- if kindIs "slice" $value -}}
  {{- range $value }}
    {{ $setting }} {{ . }}
  {{- end }}
  {{- else }}
    {{ $setting }} {{ $value }}
  {{- end }}
{{- end }}
{{- end }}