traefik:
  image:
    registry: zot.day0.sololab
    repository: library/traefik
    tag: v3.0.1
  containerSecurityContext:
    enabled: true
    seLinuxOptions:
      type: spc_t
  staticConfiguration:
    serversTransport:
      rootCAs:
        - /etc/traefik/tls/ca.crt
    entryPoints:
      web:
        forwardedHeaders:
          trustedIPs:
            - "0.0.0.0/0"
      webSecure:
        forwardedHeaders:
          trustedIPs:
            - "0.0.0.0/0"
    log:
      level: DEBUG
  dynamicConfigurationFiles:
    # https://traefik.io/blog/traefik-2-tls-101-23b4fbee81f1/
    tlsCerts.yaml:
      tls:
        certificates:
          - certFile: /etc/traefik/tls/dashboard.crt
            keyFile: /etc/traefik/tls/dashboard.key
  tls:
    mountPath: /etc/traefik/tls
    contents:
      ca.crt: "" # set from helm --set
      dashboard.crt: "" # set from helm --set
      dashboard.key: "" # set from helm --set
  podLabels:
    traefik.enable: true
    traefik.http.middlewares.userPass.basicauth.users: admin:$apr1$/F5ai.wT$7nFJWh4F7ZA0qoY.JZ69l1
    traefik.http.routers.dashboard-redirect.entrypoints: web
    traefik.http.routers.dashboard-redirect.rule: "Host(`traefik.day0.sololab`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
    traefik.http.routers.dashboard-redirect.middlewares: toHttps@file
    traefik.http.routers.dashboard.entryPoints: webSecure
    traefik.http.routers.dashboard.tls: true
    traefik.http.routers.dashboard.rule: "Host(`traefik.day0.sololab`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
    traefik.http.routers.dashboard.service: api@internal
    traefik.http.routers.dashboard.middlewares: userPass
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
    - name: LEGO_CA_CERTIFICATES
      value: /etc/traefik/tls/ca.crt
    - name: LEGO_CA_SYSTEM_CERT_POOL
      value: "true"
