# Default values for 389ds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

# -- ref: https://directory.fedoraproject.org/docs/389ds/howto/howto-deploy-389ds-on-openshift.html
directoryServer:
  imagePullSecrets: []

  # -- Init container is required to change the permissions after a persistent volume is mounted.
  # -- Otherwise dscontainer will be denied to create subdirectories and will fail to start.
  # -- really?
  initContainerImage: 
    enabled: false
    repository: busybox
    pullPolicy: IfNotPresent
    # -- Overrides the image tag  whose default is "stable"
    tag: "stable"
    command: ["sh", "-c", "chown -R 389:389 /data"]

  # -- The 389ds container image  
  image: 
    repository: 389ds/dirsrv
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000
  
  # -- securityContext for 389ds container, should uncomment below content if initContainerImage is enabled
  securityContext: {}
    # runAsUser: 389
    # fsGroup: 389  

  # @ignored
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # -- not recommand to enable
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  # @ignored
  nodeSelector: {}

  # @ignored
  tolerations: []

  # @ignored
  affinity: {}

  # -- 389ds's application config
  env:
    # -- set cn=Directory Manager’s password
    DS_DM_PASSWORD: "password"
    # -- set the log level for ns-slapd, default is 266354688.
    DS_ERRORLOG_LEVEL: ""
    # -- set LDBM autotune percentage (nsslapd-cache-autosize), default is 25.
    DS_MEMORY_PERCENTAGE: ""
    # -- run database reindex task (db2index). True/False
    DS_REINDEX: ""
    # -- set container startup timeout in seconds, default is 60 seconds.
    DS_STARTUP_TIMEOUT: "120"
    # -- use suffix as a basedn in dsrc file, default one is derived from the hostname.
    DS_SUFFIX_NAME: "dc=sololab"

# -- Bring your own cert for 389ds
bringYourOwnCert:
  enabled: true
  # -- Can only choose one from below 2 options
  # -- Generate your own cert from  cert-manager
  fromCertMan:
    enabled: true
    certificate:
      commonName: infra.sololab
      dnsNames:
        - infra.sololab
      issuerRef:
        name: ca-issuer
        kind: ClusterIssuer
      secretName: infra.sololab
  # -- Bring your own cert from exist secret
  fromExistSecret:
    enable: false
    existSecret: secret-name

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: LoadBalancer
  ports:
    ldap-tcp:
      enabled: true
      port: 389
      protocal: TCP
      targetPort: 3389
    ldaps-tcp:
      enabled: true
      port: 636
      protocal: TCP
      targetPort: 3636
