apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-sec-ssl
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: opendj
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $val := .Values.opendj.ssl.contents_b64 }}
  {{ $key }}: |
    {{- include "common.tplvalues.render" (dict "value" $val "context" $) | nindent 4 -}}
  {{- end }}