{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-cm-envvar
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: postgresql
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- range $env, $var := .Values.postgresql.config -}}
  {{- if $var }}
  {{ $env }}: {{ $var }}
  {{- end }}
  {{- end }}
{{- range $key, $val := .Values.postgresql.extending }}
{{- if $val }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  {{- /*https://github.com/bitnami/charts/blob/c816b8ac783cafc7664953245ab26f2c1c84b687/bitnami/clickhouse/templates/pdb.yaml#L9*/}}
  name: {{ template "common.names.fullname" $ }}-cm-extending-{{$key}}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: postgresql
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- range $name, $content := $val }}
  {{ $name }}: |
    {{- include "common.tplvalues.render" (dict "value" $content "context" $) | nindent 4 -}}
  {{- end }}
{{- end }}
{{- end }}