## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

## @section Common parameters
##
## @param nameOverride String to partially override common.names.name
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}

## @param loki.workloadKind specify the deploy kind： Pod, or Deployment
workloadKind: Pod
## @section %%MAIN_CONTAINER%% Parameters
##

## %%MAIN_CONTAINER/POD_DESCRIPTION%%
##
loki:
  ## Bitnami %%MAIN_CONTAINER%% image
  ## ref: https://hub.docker.com/r/grafana/loki/tags/
  ## @param loki.image.registry %%MAIN_CONTAINER%% image registry
  ## @param loki.image.repository %%MAIN_CONTAINER%% image repository
  ## @param loki.image.tag %%MAIN_CONTAINER%% image tag (immutable tags are recommended)
  ## @param loki.image.digest %%MAIN_CONTAINER%% image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag image tag (immutable tags are recommended)
  ## @param loki.image.pullPolicy %%MAIN_CONTAINER%% image pull policy
  ## @param loki.image.pullSecrets %%MAIN_CONTAINER%% image pull secrets
  ##
  image:
    registry: docker.io
    repository: grafana/loki
    tag: 3.5.0
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
  ## @param loki.podRestartPolicy specify the pod restart policy if workloadKind set to Pod
  ## available options: Always, OnFailure, Never
  podRestartPolicy: Never
  ## @param loki.replicaCount Number of loki replicas to deploy
  ##
  replicaCount: 1
  ## @param loki.containerPorts loki container port to expose to host
  ## ref: https://grafana.com/docs/loki/v3.5.x/configure/#server:~:text=%2Dserver.http%2Dlisten%2Dport
  ## ref: https://grafana.com/docs/loki/v3.5.x/configure/#server:~:text=listen%2Dport%0A%5B-,grpc_listen_port,-%3A%20%3Cint%3E
  ## e.g.
  ## containerPorts:
  ##   - name: http
  ##     containerPort: 3100
  ##     hostPort: 3100
  ##     hostIP: 192.168.255.10
  ##     protocol: TCP
  ##
  containerPorts:
    - name: http
      containerPort: 3100
      hostPort: 3100
      protocol: TCP
    - name: grpc
      containerPort: 9095
      hostPort: 9095
      protocol: TCP
  ## Configure extra options for loki containers' liveness and readiness probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
  ## ref: https://community.grafana.com/t/loki-healthcheck-in-docker-compose/117767
  ## @param loki.livenessProbe.enabled Enable livenessProbe on loki containers
  ## @param loki.livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  ## @param loki.livenessProbe.periodSeconds Period seconds for livenessProbe
  ## @param loki.livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  ## @param loki.livenessProbe.failureThreshold Failure threshold for livenessProbe
  ## @param loki.livenessProbe.successThreshold Success threshold for livenessProbe
  ##
  livenessProbe:
    enabled: true
    initialDelaySeconds: 3
    periodSeconds: 600
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - sh
        - -c
        - |
          wget --quiet --tries=1 --output-document=- http://localhost:3100/ready | grep -q -w ready
  ## @param loki.readinessProbe.enabled Enable readinessProbe on loki containers
  ## @param loki.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  ## @param loki.readinessProbe.periodSeconds Period seconds for readinessProbe
  ## @param loki.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  ## @param loki.readinessProbe.failureThreshold Failure threshold for readinessProbe
  ## @param loki.readinessProbe.successThreshold Success threshold for readinessProbe
  ## note: podman not support readinessProbe currently
  ##
  readinessProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param loki.startupProbe.enabled Enable startupProbe on loki containers
  ## @param loki.startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
  ## @param loki.startupProbe.periodSeconds Period seconds for startupProbe
  ## @param loki.startupProbe.timeoutSeconds Timeout seconds for startupProbe
  ## @param loki.startupProbe.failureThreshold Failure threshold for startupProbe
  ## @param loki.startupProbe.successThreshold Success threshold for startupProbe
  ##
  startupProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param loki.customLivenessProbe Custom livenessProbe that overrides the default one
  ##
  customLivenessProbe: {}
  ## @param loki.customReadinessProbe Custom readinessProbe that overrides the default one
  ##
  customReadinessProbe: {}
  ## @param loki.customStartupProbe Custom startupProbe that overrides the default one
  ##
  customStartupProbe: {}
  ## loki resource requests and limits
  ## ref: http://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  ## @param loki.resourcesPreset Set loki container resources according to one common preset (allowed values: none, nano, small, medium, large, xlarge, 2xlarge). This is ignored if loki.resources is set (loki.resources is recommended for production).
  ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  ##
  resourcesPreset: "nano"
  ## @param loki.resources Set loki container requests and limits for different resources like CPU or memory (essential for production workloads)
  ## Example:
  ## resources:
  ##   requests:
  ##     cpu: 2
  ##     memory: 512Mi
  ##   limits:
  ##     cpu: 3
  ##     memory: 1024Mi
  ##
  resources: {}
  ## Configure Pods Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  ## @param loki.podSecurityContext.enabled Enabled loki pods' Security Context
  ## @param loki.podSecurityContext.fsGroup Set loki pod's Security Context fsGroup
  ## note: podman kube play does not support fsGroup yet
  ##
  podSecurityContext:
    enabled: false
    # fsGroup: 1001
  ## Configure Container Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param loki.containerSecurityContext.enabled Enabled loki containers' Security Context
  ## @param loki.containerSecurityContext.runAsUser Set loki containers' Security Context runAsUser
  ## @param loki.containerSecurityContext.runAsNonRoot Set loki containers' Security Context runAsNonRoot
  ## @param loki.containerSecurityContext.readOnlyRootFilesystem Set loki containers' Security Context runAsNonRoot
  ##
  containerSecurityContext:
    enabled: false
    runAsUser: 10001
    runAsNonRoot: true
    readOnlyRootFilesystem: false

  # %%OTHER_PARAMETERS_RELATED_TO_THIS_CONTAINER/POD%%
  ## @param loki.config loki config file which will host in /etc/loki/local-config.yaml
  ## ref: https://github.com/grafana/loki/blob/v3.5.0/cmd/loki/Dockerfile#L22
  ## ref: https://github.com/grafana/loki/blob/v3.5.0/cmd/loki/loki-docker-config.yaml
  ## ref: https://grafana.com/docs/loki/v3.5.x/configure/#supported-contents-and-default-values-of-lokiyaml
  ## ref: https://grafana.com/docs/loki/latest/get-started/deployment-modes/
  ##
  config:
    ## @param loki.config.auth_enabled Enables authentication through the X-Scope-OrgID header, which must be present
    ## if true. If false, the OrgID will always be set to 'fake'.
    ##
    auth_enabled: false
    ## @param loki.config.common Common configuration to be shared between multiple modules.
    ## If a more specific configuration is given in other sections, the related configuration within this section will be ignored.
    ## ref: https://grafana.com/docs/loki/v3.5.x/configure/#common
    ## ref: https://github.com/grafana/loki/blob/v3.5.0/production/helm/loki/values.yaml
    ##
    common:
      instance_addr: 127.0.0.1
      path_prefix: /var/loki
      ## @param loki.config.common.storage config storage backend for the general storage
      ##
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    ruler:
      alertmanager_url: http://localhost:9093
    ## @param loki.config.schema_config Configures the chunk index schema and where it is stored.
    ## ref: https://grafana.com/docs/loki/v3.5.x/configure/#schema_config
    ##
    schema_config:
      ## @param loki.config.schema_config.configs list of period_configs
      ##
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    ## @param loki.config.server Configures the server of the launched module(s).
    ## ref: https://grafana.com/docs/loki/v3.5.x/configure/#server
    ##
    server:
      http_listen_port: 3100

  ## @param loki.tls secret setting of cert and key or whatever tls content will set in the container
  ##
  tls:
    ## @param loki.tls.mountPath secret mount path (dir) setting of cert and key or whatever tls content will set in the container
    ## this config should match with config under grafana.configFile.server.cert_key and grafana.configFile.server.cert_file if any
    ##
    mountPath: /etc/loki/certs
    ## @param loki.tls.contents secret content of cert and key or whatever tls content will set in the container
    ## You can set the content key as whatever file name you like
    ## But the tls set in configFiles above must match with the settings here
    ## key and certificate should start with -----BEGIN CERTIFICATE----- or -----BEGIN RSA PRIVATE KEY-----
    ## e.g.
    ## contents:
    ##  loki.crt: ""
    ##  loki.key: ""
    ##
    contents: {}
  ## @param loki.existingConfigmap The name of an existing ConfigMap with your custom configuration for loki
  ##
  existingConfigmap:
  ## @param loki.command Override default container command (useful when using custom images)
  ##
  command: []
  ## @param loki.args Override default container args (useful when using custom images)
  ##
  args: []
  ## @param loki.hostAliases loki pods host aliases
  ## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
  ##
  hostAliases: []
  ## @param loki.podLabels Extra labels for loki pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  ##
  podLabels: {}
  ## @param loki.podAnnotations Annotations for loki pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ## ref: https://github.com/grafana/loki/blob/v3.5.0/cmd/loki/Dockerfile#L26-L27
  ##
  podAnnotations:
    io.podman.annotations.userns: keep-id:uid=10001,gid=10001
  ## Autoscaling configuration
  ## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  ## @param loki.autoscaling.enabled Enable autoscaling for loki
  ## @param loki.autoscaling.minReplicas Minimum number of loki replicas
  ## @param loki.autoscaling.maxReplicas Maximum number of loki replicas
  ## @param loki.autoscaling.targetCPU Target CPU utilization percentage
  ## @param loki.autoscaling.targetMemory Target Memory utilization percentage
  ##
  autoscaling:
    enabled: false
    minReplicas: ""
    maxReplicas: ""
    targetCPU: ""
    targetMemory: ""

  ## @param loki.extraEnvVars Array with extra environment variables to add to loki nodes
  ## e.g:
  ## extraEnvVars:
  ##   - name: FOO
  ##     value: "bar"
  ##
  extraEnvVars: []
  ## @param loki.extraEnvVarsCM Name of existing ConfigMap containing extra env vars for loki nodes
  ##
  extraEnvVarsCM: ""
  ## @param loki.extraEnvVarsSecret Name of existing Secret containing extra env vars for loki nodes
  ##
  extraEnvVarsSecret: ""
  ## @param loki.extraVolumes Optionally specify extra list of additional volumes for the loki pod(s)
  ##
  extraVolumes: []
  ## @param loki.extraVolumeMounts Optionally specify extra list of additional volumeMounts for the loki container(s)
  ##
  extraVolumeMounts: []
  ## @param loki.sidecars Add additional sidecar containers to the loki pod(s)
  ## e.g:
  ## sidecars:
  ##   - name: your-image-name
  ##     image: your-image
  ##     imagePullPolicy: Always
  ##     ports:
  ##       - name: portname
  ##         containerPort: 1234
  ##
  sidecars: []
  ## @param loki.initContainers Add additional init containers to the loki pod(s)
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
  ## e.g:
  ## initContainers:
  ##  - name: your-image-name
  ##    image: your-image
  ##    imagePullPolicy: Always
  ##    command: ['sh', '-c', 'echo "hello world"']
  ##
  initContainers: []

## @section Persistence Parameters
##

## Enable persistence using Persistent Volume Claims
## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## @param persistence.enabled Enable persistence using Persistent Volume Claims
  ##
  enabled: true
  ## @param persistence.mountPath Path to mount the volume at.
  ##
  mountPath: /var/loki
  ## @param persistence.subPath The subdirectory of the volume to mount to, useful in dev environments and one PV for multiple services
  ##
  subPath: ""
  ## @param persistence.storageClass Storage class of backing PVC
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: ""
  ## @param persistence.annotations Persistent Volume Claim annotations
  ##
  annotations: {}
  ## @param persistence.accessModes Persistent Volume Access Modes
  ##
  accessModes:
    - ReadWriteOnce
  ## @param persistence.size Size of data volume
  ##
  size: 8Gi
  ## @param persistence.existingClaim The name of an existing PVC to use for persistence
  ##
  existingClaim: ""
## @section Init Container Parameters
##

## 'volumePermissions' init container parameters
## Changes the owner and group of the persistent volume mount point to runAsUser:fsGroup values
##   based on the *podSecurityContext/*containerSecurityContext parameters
##
volumePermissions:
  ## @param volumePermissions.enabled Enable init container that changes the owner/group of the PV mount point to `runAsUser:fsGroup`
  ##
  enabled: false
  ## OS Shell + Utility image
  ## ref: https://hub.docker.com/r/bitnami/os-shell/tags/
  ## @param volumePermissions.image.registry OS Shell + Utility image registry
  ## @param volumePermissions.image.repository OS Shell + Utility image repository
  ## @param volumePermissions.image.tag OS Shell + Utility image tag (immutable tags are recommended)
  ## @param volumePermissions.image.pullPolicy OS Shell + Utility image pull policy
  ## @param volumePermissions.image.pullSecrets OS Shell + Utility image pull secrets
  ##
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: 11-debian-11-r%%IMAGE_REVISION%%
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
  ## Init container's resource requests and limits
  ## ref: http://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  ## @param volumePermissions.resourcesPreset Set init container resources according to one common preset (allowed values: none, nano, small, medium, large, xlarge, 2xlarge). This is ignored if volumePermissions.resources is set (volumePermissions.resources is recommended for production).
  ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  ##
  resourcesPreset: "nano"
  ## @param volumePermissions.resources Set init container requests and limits for different resources like CPU or memory (essential for production workloads)
  ## Example:
  ## resources:
  ##   requests:
  ##     cpu: 2
  ##     memory: 512Mi
  ##   limits:
  ##     cpu: 3
  ##     memory: 1024Mi
  ##
  resources: {}
  ## Init container Container Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param volumePermissions.containerSecurityContext.runAsUser Set init container's Security Context runAsUser
  ## NOTE: when runAsUser is set to special value "auto", init container will try to chown the
  ##   data folder to auto-determined user&group, using commands: `id -u`:`id -G | cut -d" " -f2`
  ##   "auto" is especially useful for OpenShift which has scc with dynamic user ids (and 0 is not allowed)
  ##
  containerSecurityContext:
    runAsUser: 0

## @section Other Parameters
##

## %%SUBCHART_CONTAINER/POD_DESCRIPTION%%
##
# %%SUBCHART_NAME%%:
SUBCHART_NAME:
  enabled: false
  # %%OTHER_PARAMETERS_RELATED_TO_THIS_SUBCHART%%
