{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-cm
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: zot
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  config.json: |
{{ toJson .Values.zot.config | indent 4 }}
{{- if .Values.zot.htpasswdCredentials }}
  htpasswd: |
{{- range $i, $credential := .Values.zot.htpasswdCredentials }}
    {{ htpasswd $credential.username $credential.password }}
{{ end -}}
{{- end }}