apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}-dns-tcp
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.dns.type }}
  ports:
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "powerdns.selectorLabels" . | nindent 4 }}
