## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

## @section Common parameters
##
## @param nameOverride String to partially override common.names.name
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}

## @param socat.deployKind specify the deploy kind： Pod, or Deployment
deployKind: Pod
## @section socat Parameters
##

## %%MAIN_CONTAINER/POD_DESCRIPTION%%
##
socat:
  ## Bitnami socat image
  ## ref: https://hub.docker.com/r/alpine/socat/tags
  ## @param socat.image.registry socat image registry
  ## @param socat.image.repository socat image repository
  ## @param socat.image.tag socat image tag (immutable tags are recommended)
  ## @param socat.image.digest socat image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag image tag (immutable tags are recommended)
  ## @param socat.image.pullPolicy socat image pull policy
  ## @param socat.image.pullSecrets socat image pull secrets
  ##
  image:
    registry: docker.io
    repository: alpine/socat
    tag: latest
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
  ## @param socat.podRestartPolicy specify the pod restart policy if deployKind set to Pod
  ## available options: Always, OnFailure, Never
  podRestartPolicy: Never
  ## @param socat.replicaCount Number of socat replicas to deploy
  ##
  replicaCount: 1
  ## @param socat.containerPorts socat container port to expose to host
  ## containerPorts:
  ##   - name: http
  ##     containerPort: 80
  ##     hostIP: 192.168.255.10
  ##     protocol: TCP
  ##   - name: https
  ##     containerPort: 443
  ##     hostIP: 192.168.255.10
  ##     protocol: TCP
  ##
  containerPorts: {}
  ## Configure extra options for socat containers' liveness and readiness probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
  ## @param socat.livenessProbe.enabled Enable livenessProbe on socat containers
  ## @param socat.livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  ## @param socat.livenessProbe.periodSeconds Period seconds for livenessProbe
  ## @param socat.livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  ## @param socat.livenessProbe.failureThreshold Failure threshold for livenessProbe
  ## @param socat.livenessProbe.successThreshold Success threshold for livenessProbe
  ##
  livenessProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param socat.readinessProbe.enabled Enable readinessProbe on socat containers
  ## @param socat.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  ## @param socat.readinessProbe.periodSeconds Period seconds for readinessProbe
  ## @param socat.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  ## @param socat.readinessProbe.failureThreshold Failure threshold for readinessProbe
  ## @param socat.readinessProbe.successThreshold Success threshold for readinessProbe
  ##
  readinessProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param socat.startupProbe.enabled Enable startupProbe on socat containers
  ## @param socat.startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
  ## @param socat.startupProbe.periodSeconds Period seconds for startupProbe
  ## @param socat.startupProbe.timeoutSeconds Timeout seconds for startupProbe
  ## @param socat.startupProbe.failureThreshold Failure threshold for startupProbe
  ## @param socat.startupProbe.successThreshold Success threshold for startupProbe
  ##
  startupProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param socat.customLivenessProbe Custom livenessProbe that overrides the default one
  ##
  customLivenessProbe: {}
  ## @param socat.customReadinessProbe Custom readinessProbe that overrides the default one
  ##
  customReadinessProbe: {}
  ## @param socat.customStartupProbe Custom startupProbe that overrides the default one
  ##
  customStartupProbe: {}
  ## socat resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ## @param socat.resources.limits The resources limits for the socat containers
  ## @param socat.resources.requests The requested resources for the socat containers
  ##
  resources:
    limits: {}
    requests: {}
  ## Configure Pods Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  ## @param socat.podSecurityContext.enabled Enabled socat pods' Security Context
  ## @param socat.podSecurityContext.fsGroup Set socat pod's Security Context fsGroup
  ##
  podSecurityContext:
    enabled: false
    fsGroup: 1001
  ## Configure Container Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param socat.containerSecurityContext.enabled Enabled socat containers' Security Context
  ## @param socat.containerSecurityContext.runAsUser Set socat containers' Security Context runAsUser
  ## @param socat.containerSecurityContext.runAsNonRoot Set socat containers' Security Context runAsNonRoot
  ## @param socat.containerSecurityContext.readOnlyRootFilesystem Set socat containers' Security Context runAsNonRoot
  ##
  containerSecurityContext:
    enabled: false
    runAsUser: 1001
    runAsNonRoot: true
    readOnlyRootFilesystem: false

  # %%OTHER_PARAMETERS_RELATED_TO_THIS_CONTAINER/POD%%

  ## @param socat.existingConfigmap The name of an existing ConfigMap with your custom configuration for socat
  ##
  existingConfigmap:
  ## @param socat.command Override default container command (useful when using custom images)
  ##
  command: []
  ## @param socat.args Override default container args (useful when using custom images)
  ## ref: https://github.com/alpine-docker/multi-arch-libs/tree/master/socat#example
  ##
  args:
    - tcp-listen:2375
    - fork
    - reuseaddr
    - unix-connect:/var/run/docker.sock
  ## @param socat.hostAliases socat pods host aliases
  ## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
  ##
  hostAliases: []
  ## @param socat.podLabels Extra labels for socat pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  ##
  podLabels: {}
  ## @param socat.podAnnotations Annotations for socat pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations: {}
  ## Autoscaling configuration
  ## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  ## @param socat.autoscaling.enabled Enable autoscaling for socat
  ## @param socat.autoscaling.minReplicas Minimum number of socat replicas
  ## @param socat.autoscaling.maxReplicas Maximum number of socat replicas
  ## @param socat.autoscaling.targetCPU Target CPU utilization percentage
  ## @param socat.autoscaling.targetMemory Target Memory utilization percentage
  ##
  autoscaling:
    enabled: false
    minReplicas: ""
    maxReplicas: ""
    targetCPU: ""
    targetMemory: ""

  ## @param socat.extraEnvVars Array with extra environment variables to add to socat nodes
  ## e.g:
  ## extraEnvVars:
  ##   - name: FOO
  ##     value: "bar"
  ##
  extraEnvVars: []
  ## @param socat.extraEnvVarsCM Name of existing ConfigMap containing extra env vars for socat nodes
  ##
  extraEnvVarsCM: ""
  ## @param socat.extraEnvVarsSecret Name of existing Secret containing extra env vars for socat nodes
  ##
  extraEnvVarsSecret: ""
  ## @param socat.extraVolumes Optionally specify extra list of additional volumes for the socat pod(s)
  ##
  extraVolumes: []
  ## @param socat.extraVolumeMounts Optionally specify extra list of additional volumeMounts for the socat container(s)
  ##
  extraVolumeMounts: []
  ## @param socat.sidecars Add additional sidecar containers to the socat pod(s)
  ## e.g:
  ## sidecars:
  ##   - name: your-image-name
  ##     image: your-image
  ##     imagePullPolicy: Always
  ##     ports:
  ##       - name: portname
  ##         containerPort: 1234
  ##
  sidecars: []
  ## @param socat.initContainers Add additional init containers to the socat pod(s)
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
  ## e.g:
  ## initContainers:
  ##  - name: your-image-name
  ##    image: your-image
  ##    imagePullPolicy: Always
  ##    command: ['sh', '-c', 'echo "hello world"']
  ##
  initContainers: []

## @section Persistence Parameters
##

## Enable persistence using Persistent Volume Claims
## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## @param persistence.enabled Enable persistence using Persistent Volume Claims
  ##
  enabled: true
  ## @param persistence.mountPath Path to mount the volume at.
  ##
  mountPath: /bitnami/socat/data
  ## @param persistence.subPath The subdirectory of the volume to mount to, useful in dev environments and one PV for multiple services
  ##
  subPath: ""
  ## @param persistence.storageClass Storage class of backing PVC
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: ""
  ## @param persistence.annotations Persistent Volume Claim annotations
  ##
  annotations: {}
  ## @param persistence.accessModes Persistent Volume Access Modes
  ##
  accessModes:
    - ReadWriteOnce
  ## @param persistence.size Size of data volume
  ##
  size: 8Gi
  ## @param persistence.existingClaim The name of an existing PVC to use for persistence
  ##
  existingClaim: ""
  ## @param persistence.dataSource Custom PVC data source
  ##
  dataSource: {}
## @section Init Container Parameters
##

## 'volumePermissions' init container parameters
## Changes the owner and group of the persistent volume mount point to runAsUser:fsGroup values
##   based on the *podSecurityContext/*containerSecurityContext parameters
##
volumePermissions:
  ## @param volumePermissions.enabled Enable init container that changes the owner/group of the PV mount point to `runAsUser:fsGroup`
  ##
  enabled: false
  ## OS Shell + Utility image
  ## ref: https://hub.docker.com/r/bitnami/os-shell/tags/
  ## @param volumePermissions.image.registry OS Shell + Utility image registry
  ## @param volumePermissions.image.repository OS Shell + Utility image repository
  ## @param volumePermissions.image.tag OS Shell + Utility image tag (immutable tags are recommended)
  ## @param volumePermissions.image.pullPolicy OS Shell + Utility image pull policy
  ## @param volumePermissions.image.pullSecrets OS Shell + Utility image pull secrets
  ##
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: 11-debian-11-r%%IMAGE_REVISION%%
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
  ## Init container's resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ## @param volumePermissions.resources.limits The resources limits for the init container
  ## @param volumePermissions.resources.requests The requested resources for the init container
  ##
  resources:
    limits: {}
    requests: {}
  ## Init container Container Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param volumePermissions.containerSecurityContext.runAsUser Set init container's Security Context runAsUser
  ## NOTE: when runAsUser is set to special value "auto", init container will try to chown the
  ##   data folder to auto-determined user&group, using commands: `id -u`:`id -G | cut -d" " -f2`
  ##   "auto" is especially useful for OpenShift which has scc with dynamic user ids (and 0 is not allowed)
  ##
  containerSecurityContext:
    runAsUser: 0
## @section Other Parameters
##

