{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-cm
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: nfs-ganesha
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  ganesha.conf: |
{{- range $section, $values := $config -}}
    {{ $section }} {
{{- range $key, $value := $values }}
    {{- if kindIs "map" $value }}
    {{ $key }} {
        {{- range $subKey, $subValue := $value }}
        {{ $subKey }} = {{ $subValue | quote }};
        {{- end }}
    }
    {{- else if kindIs "slice" $value }}
    {{ $key }} = {{ $value | join ", " }};
    {{- else }}
    {{ $key }} = {{ $value | quote }};
    {{- end }}
{{- end }}
}
{{ end -}}