annotations:
  # CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE
  # https://github.com/bitnami/charts/blob/main/CHART_CATEGORIES
  category: Database
  licenses: Apache-2.0
apiVersion: v2
appVersion: v3.6.0
dependencies:
  - name: common
    repository: file://../common
    version: 2.x.x
description: etcd is a distributed key-value store designed to securely store data across a cluster. etcd is widely used in production on account of its reliability, fault-tolerance and ease of use.
home: https://github.com/fsdrw08/helm-charts
icon: https://bitnami.com/assets/stacks/etcd/img/etcd-stack-220x234.png
keywords:
  - etcd
  - cluster
  - database
  - cache
  - key-value
maintainers:
  - name: Windom WU
    url: https://github.com/fsdrw08/helm-charts
name: etcd
sources:
  - https://github.com/fsdrw08/helm-charts/tree/main/charts/etcd
  - https://github.com/etcd-io/etcd
version: 0.1.0
