annotations:
  # CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE
  # https://github.com/bitnami/charts/blob/main/CHART_CATEGORIES
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.7.7
dependencies:
  - name: common
    repository: file://../common
    version: 2.x.x
description: Kea DHCP server helm chart for podman kube play
home: https://github.com/fsdrw08/helm-charts
icon: https://kea.readthedocs.io/en/latest/_images/kea-logo-200.png
keywords:
  - kea
  - dhcp
  - podman kube play
maintainers:
  - name: Windom WU
    url: https://github.com/fsdrw08/helm-charts
name: kea
sources:
  - https://github.com/fsdrw08/helm-charts/kea
  - https://gitlab.isc.org/isc-projects/kea-docker
  - https://github.com/JonasAlfredsson/docker-kea/tree/main
  - https://gitlab.isc.org/isc-projects/kea
  - ...
version: 0.1.0
