## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

## @section Common parameters
##
## @param nameOverride String to partially override common.names.name
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}

## @param kea.workloadKind specify the deploy kind： Pod, or Deployment
workloadKind: Pod
## @section kea Parameters
##

## %%MAIN_CONTAINER/POD_DESCRIPTION%%
##
kea:
  ## ISC kea image
  ## ref: https://hub.docker.com/r/bitnami/%%IMAGE_NAME%%/tags/
  ## @param kea.image.registry kea image registry
  ## @param kea.image.repository kea image repository
  ## @param kea.image.tag kea image tag (immutable tags are recommended)
  ## @param kea.image.digest kea image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag image tag (immutable tags are recommended)
  ## @param kea.image.pullPolicy kea image pull policy
  ## @param kea.image.pullSecrets kea image pull secrets
  ##
  image:
    registry: docker.cloudsmith.io
    repository: isc/docker/kea-dhcp4
    tag: 2.7.6-20250129
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
  ## @param kea.podRestartPolicy specify the pod restart policy if workloadKind set to Pod
  ## available options: Always, OnFailure, Never
  podRestartPolicy: Never
  ## @param kea.replicaCount Number of kea replicas to deploy
  ##
  replicaCount: 1
  ## @param kea.containerPorts kea container port to expose to host
  ## e.g.
  ## containerPorts:
  ##   - name: http
  ##     containerPort: 80
  ##     hostPort: 80
  ##     hostIP: 192.168.255.10
  ##     protocol: TCP
  ##   - name: https
  ##     containerPort: 443
  ##     hostPort: 443
  ##     hostIP: 192.168.255.10
  ##     protocol: TCP
  ##
  containerPorts: {}
  ## Configure extra options for kea containers' liveness and readiness probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
  ## @param kea.livenessProbe.enabled Enable livenessProbe on kea containers
  ## @param kea.livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  ## @param kea.livenessProbe.periodSeconds Period seconds for livenessProbe
  ## @param kea.livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  ## @param kea.livenessProbe.failureThreshold Failure threshold for livenessProbe
  ## @param kea.livenessProbe.successThreshold Success threshold for livenessProbe
  ##
  livenessProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param kea.readinessProbe.enabled Enable readinessProbe on kea containers
  ## @param kea.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  ## @param kea.readinessProbe.periodSeconds Period seconds for readinessProbe
  ## @param kea.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  ## @param kea.readinessProbe.failureThreshold Failure threshold for readinessProbe
  ## @param kea.readinessProbe.successThreshold Success threshold for readinessProbe
  ## note: podman not support readinessProbe currently
  ##
  readinessProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param kea.startupProbe.enabled Enable startupProbe on kea containers
  ## @param kea.startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
  ## @param kea.startupProbe.periodSeconds Period seconds for startupProbe
  ## @param kea.startupProbe.timeoutSeconds Timeout seconds for startupProbe
  ## @param kea.startupProbe.failureThreshold Failure threshold for startupProbe
  ## @param kea.startupProbe.successThreshold Success threshold for startupProbe
  ##
  startupProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param kea.customLivenessProbe Custom livenessProbe that overrides the default one
  ##
  customLivenessProbe: {}
  ## @param kea.customReadinessProbe Custom readinessProbe that overrides the default one
  ##
  customReadinessProbe: {}
  ## @param kea.customStartupProbe Custom startupProbe that overrides the default one
  ##
  customStartupProbe: {}
  ## kea resource requests and limits
  ## ref: http://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  ## @param kea.resourcesPreset Set kea container resources according to one common preset (allowed values: none, nano, small, medium, large, xlarge, 2xlarge). This is ignored if kea.resources is set (kea.resources is recommended for production).
  ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  ##
  resourcesPreset: "nano"
  ## @param kea.resources Set kea container requests and limits for different resources like CPU or memory (essential for production workloads)
  ## Example:
  ## resources:
  ##   requests:
  ##     cpu: 2
  ##     memory: 512Mi
  ##   limits:
  ##     cpu: 3
  ##     memory: 1024Mi
  ##
  resources: {}
  ## Configure Pods Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  ## @param kea.podSecurityContext.enabled Enabled kea pods' Security Context
  ## @param kea.podSecurityContext.fsGroup Set kea pod's Security Context fsGroup
  ## note: podman kube play does not support fsGroup yet
  ##
  podSecurityContext:
    enabled: false
    # fsGroup: 1001
  ## Configure Container Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param kea.containerSecurityContext.enabled Enabled kea containers' Security Context
  ## @param kea.containerSecurityContext.runAsUser Set kea containers' Security Context runAsUser
  ## @param kea.containerSecurityContext.runAsNonRoot Set kea containers' Security Context runAsNonRoot
  ## @param kea.containerSecurityContext.readOnlyRootFilesystem Set kea containers' Security Context runAsNonRoot
  ##
  containerSecurityContext:
    enabled: false
    runAsUser: 1001
    runAsNonRoot: true
    readOnlyRootFilesystem: false

  configFiles:
    ## @param kea.configFiles.dhcp4.dhcp4 dhcp4 config file
    dhcp4:
      ## @param kea.configFiles.dhcp4.dhcp4.dhcp dhcp4 config block in dhcp 4 config file
      dhcp4:
        ## @param kea.configFiles.dhcp4.interfaces-config The interfaces-config map specifies the network interfaces on which the server should listen to DHCP messages.
        ## The interfaces parameter specifies a list of network interfaces on which the server should listen.
        ## ref: https://kea.readthedocs.io/en/latest/arm/dhcp4-srv.html#interface-configuration
        ##
        interfaces-config:
          ## @param kea.configFiles.dhcp4.interfaces-config.interfaces The interfaces-config map specifies the network interfaces on which the server should listen to DHCP messages.
          ## It is recommended to specify the actual interface you want to listen on, but it is possible to bind to all present.
          ##
          interfaces: ["*"]
          ## @param kea.configFiles.dhcp4.interfaces-config.dhcp-socket-type By default Kea listens using raw sockets.
          ## This ensures all packets, including those sent by directly connected clients that traffic is always relayed,
          ## it is often better to use regular UDP sockets. If you want to do that, set this to "udp".
          ##
          dhcp-socket-type: raw
        ## @param kea.configFiles.dhcp4.control-socket Kea supports control channel, which is a way to receive management commands while the server is running.
        ## This is a Unix domain socket that receives commands formatted in JSON, e.g. config-set (which sets new configuration), config-reload (which tells Kea to reload its configuration from file), statistic-get (to retrieve statistics)
        ## and many more.
        ## ref: https://kea.readthedocs.io/en/latest/arm/dhcp4-srv.html#management-api-for-the-dhcpv4-server
        ## ref: https://github.com/JonasAlfredsson/docker-kea/blob/main/examples/advanced/config/dhcp4.json
        ##
        control-socket:
          socket-type: unix
          socket-name: /kea/sockets/dhcp4.socket
        ## Specifies credentials to access lease database.
        lease-database:
          ## Lease database backend type, i.e. "memfile", "mysql", "postgresql" or "cql".
          type: memfile
          ## Name of the lease file. In case of database it specifies the database name.
          ##
          name: /kea/leases/dhcp4.csv
          ## memfile backend specific parameter specifying the interval in seconds at which lease file should be cleaned up.
          ##
          lfc-interval: 3600
  ## @param kea.existingConfigmap The name of an existing ConfigMap with your custom configuration for kea
  ##
  existingConfigmap:
  ## @param kea.command Override default container command (useful when using custom images)
  ##
  command: []
  ## @param kea.args Override default container args (useful when using custom images)
  ##
  args: []
  ## @param kea.hostAliases kea pods host aliases
  ## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
  ##
  hostAliases: []
  ## @param kea.podLabels Extra labels for kea pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  ##
  podLabels: {}
  ## @param kea.podAnnotations Annotations for kea pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations: {}
  ## Autoscaling configuration
  ## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  ## @param kea.autoscaling.enabled Enable autoscaling for kea
  ## @param kea.autoscaling.minReplicas Minimum number of kea replicas
  ## @param kea.autoscaling.maxReplicas Maximum number of kea replicas
  ## @param kea.autoscaling.targetCPU Target CPU utilization percentage
  ## @param kea.autoscaling.targetMemory Target Memory utilization percentage
  ##
  autoscaling:
    enabled: false
    minReplicas: ""
    maxReplicas: ""
    targetCPU: ""
    targetMemory: ""

  ## @param kea.extraEnvVars Array with extra environment variables to add to kea nodes
  ## e.g:
  ## extraEnvVars:
  ##   - name: FOO
  ##     value: "bar"
  ##
  extraEnvVars: []
  ## @param kea.extraEnvVarsCM Name of existing ConfigMap containing extra env vars for kea nodes
  ##
  extraEnvVarsCM: ""
  ## @param kea.extraEnvVarsSecret Name of existing Secret containing extra env vars for kea nodes
  ##
  extraEnvVarsSecret: ""
  ## @param kea.extraVolumes Optionally specify extra list of additional volumes for the kea pod(s)
  ##
  extraVolumes: []
  ## @param kea.extraVolumeMounts Optionally specify extra list of additional volumeMounts for the kea container(s)
  ##
  extraVolumeMounts: []
  ## @param kea.sidecars Add additional sidecar containers to the kea pod(s)
  ## e.g:
  ## sidecars:
  ##   - name: your-image-name
  ##     image: your-image
  ##     imagePullPolicy: Always
  ##     ports:
  ##       - name: portname
  ##         containerPort: 1234
  ##
  sidecars: []
  ## @param kea.initContainers Add additional init containers to the kea pod(s)
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
  ## e.g:
  ## initContainers:
  ##  - name: your-image-name
  ##    image: your-image
  ##    imagePullPolicy: Always
  ##    command: ['sh', '-c', 'echo "hello world"']
  ##
  initContainers: []

## @section Persistence Parameters
##

## Enable persistence using Persistent Volume Claims
## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## @param persistence.enabled Enable persistence using Persistent Volume Claims
  ##
  enabled: true
  ## @param persistence.mountPath Path to mount the volume at.
  ##
  mountPath: /bitnami/kea/data
  ## @param persistence.subPath The subdirectory of the volume to mount to, useful in dev environments and one PV for multiple services
  ##
  subPath: ""
  ## @param persistence.storageClass Storage class of backing PVC
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: ""
  ## @param persistence.annotations Persistent Volume Claim annotations
  ##
  annotations: {}
  ## @param persistence.accessModes Persistent Volume Access Modes
  ##
  accessModes:
    - ReadWriteOnce
  ## @param persistence.size Size of data volume
  ##
  size: 8Gi
  ## @param persistence.existingClaim The name of an existing PVC to use for persistence
  ##
  existingClaim: ""
## @section Init Container Parameters
##

## 'volumePermissions' init container parameters
## Changes the owner and group of the persistent volume mount point to runAsUser:fsGroup values
##   based on the *podSecurityContext/*containerSecurityContext parameters
##
volumePermissions:
  ## @param volumePermissions.enabled Enable init container that changes the owner/group of the PV mount point to `runAsUser:fsGroup`
  ##
  enabled: false
  ## OS Shell + Utility image
  ## ref: https://hub.docker.com/r/bitnami/os-shell/tags/
  ## @param volumePermissions.image.registry OS Shell + Utility image registry
  ## @param volumePermissions.image.repository OS Shell + Utility image repository
  ## @param volumePermissions.image.tag OS Shell + Utility image tag (immutable tags are recommended)
  ## @param volumePermissions.image.pullPolicy OS Shell + Utility image pull policy
  ## @param volumePermissions.image.pullSecrets OS Shell + Utility image pull secrets
  ##
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: 11-debian-11-r%%IMAGE_REVISION%%
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
  ## Init container's resource requests and limits
  ## ref: http://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  ## @param volumePermissions.resourcesPreset Set init container resources according to one common preset (allowed values: none, nano, small, medium, large, xlarge, 2xlarge). This is ignored if volumePermissions.resources is set (volumePermissions.resources is recommended for production).
  ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  ##
  resourcesPreset: "nano"
  ## @param volumePermissions.resources Set init container requests and limits for different resources like CPU or memory (essential for production workloads)
  ## Example:
  ## resources:
  ##   requests:
  ##     cpu: 2
  ##     memory: 512Mi
  ##   limits:
  ##     cpu: 3
  ##     memory: 1024Mi
  ##
  resources: {}
  ## Init container Container Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param volumePermissions.containerSecurityContext.runAsUser Set init container's Security Context runAsUser
  ## NOTE: when runAsUser is set to special value "auto", init container will try to chown the
  ##   data folder to auto-determined user&group, using commands: `id -u`:`id -G | cut -d" " -f2`
  ##   "auto" is especially useful for OpenShift which has scc with dynamic user ids (and 0 is not allowed)
  ##
  containerSecurityContext:
    runAsUser: 0

## @section Other Parameters
##

## %%SUBCHART_CONTAINER/POD_DESCRIPTION%%
##
# %%SUBCHART_NAME%%:
SUBCHART_NAME:
  enabled: false
  # %%OTHER_PARAMETERS_RELATED_TO_THIS_SUBCHART%%
