## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

## @section Common parameters
##
## @param nameOverride String to partially override common.names.name
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}

## @param dhcp4.workloadKind specify the deploy kind： Pod, or Deployment
workloadKind: Pod
## @section kea Parameters
##

## %%MAIN_CONTAINER/POD_DESCRIPTION%%
##
dhcp4:
  enabled: true
  ## ISC kea image
  ## ref: https://hub.docker.com/r/bitnami/%%IMAGE_NAME%%/tags/
  ## @param dhcp4.image.registry kea image registry
  ## @param dhcp4.image.repository kea image repository
  ## @param dhcp4.image.tag kea image tag (immutable tags are recommended)
  ## @param dhcp4.image.digest kea image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag image tag (immutable tags are recommended)
  ## @param dhcp4.image.pullPolicy kea image pull policy
  ## @param dhcp4.image.pullSecrets kea image pull secrets
  ##
  image:
    registry: docker.cloudsmith.io
    repository: isc/docker/kea-dhcp4
    tag: 2.7.6-20250129
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
  ## @param dhcp4.podRestartPolicy specify the pod restart policy if workloadKind set to Pod
  ## available options: Always, OnFailure, Never
  podRestartPolicy: Never
  ## @param dhcp4.replicaCount Number of kea replicas to deploy
  ##
  replicaCount: 1
  ## @param dhcp4.containerPorts kea container port to expose to host
  ## e.g.
  ## containerPorts:
  ##   - name: http
  ##     containerPort: 80
  ##     hostPort: 80
  ##     hostIP: 192.168.255.10
  ##     protocol: TCP
  ##   - name: https
  ##     containerPort: 443
  ##     hostPort: 443
  ##     hostIP: 192.168.255.10
  ##     protocol: TCP
  ##
  containerPorts: {}
  ## Configure extra options for kea containers' liveness and readiness probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
  ## @param dhcp4.livenessProbe.enabled Enable livenessProbe on kea containers
  ## @param dhcp4.livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  ## @param dhcp4.livenessProbe.periodSeconds Period seconds for livenessProbe
  ## @param dhcp4.livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  ## @param dhcp4.livenessProbe.failureThreshold Failure threshold for livenessProbe
  ## @param dhcp4.livenessProbe.successThreshold Success threshold for livenessProbe
  ##
  livenessProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param dhcp4.readinessProbe.enabled Enable readinessProbe on kea containers
  ## @param dhcp4.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  ## @param dhcp4.readinessProbe.periodSeconds Period seconds for readinessProbe
  ## @param dhcp4.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  ## @param dhcp4.readinessProbe.failureThreshold Failure threshold for readinessProbe
  ## @param dhcp4.readinessProbe.successThreshold Success threshold for readinessProbe
  ## note: podman not support readinessProbe currently
  ##
  readinessProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param dhcp4.startupProbe.enabled Enable startupProbe on kea containers
  ## @param dhcp4.startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
  ## @param dhcp4.startupProbe.periodSeconds Period seconds for startupProbe
  ## @param dhcp4.startupProbe.timeoutSeconds Timeout seconds for startupProbe
  ## @param dhcp4.startupProbe.failureThreshold Failure threshold for startupProbe
  ## @param dhcp4.startupProbe.successThreshold Success threshold for startupProbe
  ##
  startupProbe:
    enabled: false
    initialDelaySeconds: foo
    periodSeconds: bar
    timeoutSeconds: foo
    failureThreshold: bar
    successThreshold: foo
  ## @param dhcp4.customLivenessProbe Custom livenessProbe that overrides the default one
  ##
  customLivenessProbe: {}
  ## @param dhcp4.customReadinessProbe Custom readinessProbe that overrides the default one
  ##
  customReadinessProbe: {}
  ## @param dhcp4.customStartupProbe Custom startupProbe that overrides the default one
  ##
  customStartupProbe: {}
  ## kea resource requests and limits
  ## ref: http://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  ## @param dhcp4.resourcesPreset Set kea container resources according to one common preset (allowed values: none, nano, small, medium, large, xlarge, 2xlarge). This is ignored if dhcp4.resources is set (kea.resources is recommended for production).
  ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  ##
  resourcesPreset: "nano"
  ## @param dhcp4.resources Set kea container requests and limits for different resources like CPU or memory (essential for production workloads)
  ## Example:
  ## resources:
  ##   requests:
  ##     cpu: 2
  ##     memory: 512Mi
  ##   limits:
  ##     cpu: 3
  ##     memory: 1024Mi
  ##
  resources: {}
  ## Configure Pods Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  ## @param dhcp4.podSecurityContext.enabled Enabled kea pods' Security Context
  ## @param dhcp4.podSecurityContext.fsGroup Set kea pod's Security Context fsGroup
  ## note: podman kube play does not support fsGroup yet
  ##
  podSecurityContext:
    enabled: false
    # fsGroup: 1001
  ## Configure Container Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param dhcp4.containerSecurityContext.enabled Enabled kea containers' Security Context
  ## @param dhcp4.containerSecurityContext.runAsUser Set kea containers' Security Context runAsUser
  ## @param dhcp4.containerSecurityContext.runAsNonRoot Set kea containers' Security Context runAsNonRoot
  ## @param dhcp4.containerSecurityContext.readOnlyRootFilesystem Set kea containers' Security Context runAsNonRoot
  ##
  containerSecurityContext:
    enabled: false
    runAsUser: 1001
    runAsNonRoot: true
    readOnlyRootFilesystem: false

  configFiles:
    ## @param dhcp4.configFiles.kea-dhcp4 dhcp4 config file which will place in /etc/kea/kea-dhcp4.conf
    ## ref: https://gitlab.isc.org/isc-projects/kea-docker/-/blob/master/kea-dhcp4/kea-dhcp4.conf
    ##
    kea-dhcp4:
      ## @param dhcp4.configFiles.kea-dhcp4.Dhcp4 Kea DHCPv4 server configuration begins here.
      ## ref: https://github.com/isc-projects/kea/blob/master/doc/examples/kea4/all-keys.json
      ##
      Dhcp4:
        subnet4:
          - subnet: 192.168.50.0/24
            pools:
              - pool: 192.168.50.1-192.168.50.100
            id: 1
            interface: eth0
        interfaces-config:
          interfaces:
            - eth0
          service-sockets-max-retries: 5
          service-sockets-require-all: true
        control-sockets:
          - socket-type: unix
            socket-name: /run/kea/control_socket_4
          - socket-type: http
            socket-address: 0.0.0.0
            socket-port: 8000
        renew-timer: 1000
        rebind-timer: 2000
        valid-lifetime: 4000
        loggers:
          - name: kea-dhcp4
            output_options:
              - output: stdout
            severity: INFO
        lease-database:
          type: memfile

  ## @param dhcp4.existingConfigmap The name of an existing ConfigMap with your custom configuration for kea
  ##
  existingConfigmap:
  ## @param dhcp4.command Override default container command (useful when using custom images)
  ##
  command: []
  ## @param dhcp4.args Override default container args (useful when using custom images)
  ##
  args: []
  ## @param dhcp4.hostAliases kea pods host aliases
  ## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
  ##
  hostAliases: []
  ## @param dhcp4.podLabels Extra labels for kea pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  ##
  podLabels: {}
  ## @param dhcp4.podAnnotations Annotations for kea pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations: {}
  ## Autoscaling configuration
  ## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  ## @param dhcp4.autoscaling.enabled Enable autoscaling for kea
  ## @param dhcp4.autoscaling.minReplicas Minimum number of kea replicas
  ## @param dhcp4.autoscaling.maxReplicas Maximum number of kea replicas
  ## @param dhcp4.autoscaling.targetCPU Target CPU utilization percentage
  ## @param dhcp4.autoscaling.targetMemory Target Memory utilization percentage
  ##
  autoscaling:
    enabled: false
    minReplicas: ""
    maxReplicas: ""
    targetCPU: ""
    targetMemory: ""

  ## @param dhcp4.extraEnvVars Array with extra environment variables to add to kea nodes
  ## e.g:
  ## extraEnvVars:
  ##   - name: FOO
  ##     value: "bar"
  ##
  extraEnvVars: []
  ## @param dhcp4.extraEnvVarsCM Name of existing ConfigMap containing extra env vars for kea nodes
  ##
  extraEnvVarsCM: ""
  ## @param dhcp4.extraEnvVarsSecret Name of existing Secret containing extra env vars for kea nodes
  ##
  extraEnvVarsSecret: ""
  ## @param dhcp4.extraVolumes Optionally specify extra list of additional volumes for the kea pod(s)
  ##
  extraVolumes: []
  ## @param dhcp4.extraVolumeMounts Optionally specify extra list of additional volumeMounts for the kea container(s)
  ##
  extraVolumeMounts: []
  ## @param dhcp4.sidecars Add additional sidecar containers to the kea pod(s)
  ## e.g:
  ## sidecars:
  ##   - name: your-image-name
  ##     image: your-image
  ##     imagePullPolicy: Always
  ##     ports:
  ##       - name: portname
  ##         containerPort: 1234
  ##
  sidecars: []
  ## @param dhcp4.initContainers Add additional init containers to the kea pod(s)
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
  ## e.g:
  ## initContainers:
  ##  - name: your-image-name
  ##    image: your-image
  ##    imagePullPolicy: Always
  ##    command: ['sh', '-c', 'echo "hello world"']
  ##
  initContainers: []

## @section Persistence Parameters
##

## Enable persistence using Persistent Volume Claims
## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## @param persistence.enabled Enable persistence using Persistent Volume Claims
  ##
  enabled: true
  ## @param persistence.mountPath Path to mount the volume at.
  ##
  mountPath: /bitnami/kea/data
  ## @param persistence.subPath The subdirectory of the volume to mount to, useful in dev environments and one PV for multiple services
  ##
  subPath: ""
  ## @param persistence.storageClass Storage class of backing PVC
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: ""
  ## @param persistence.annotations Persistent Volume Claim annotations
  ##
  annotations: {}
  ## @param persistence.accessModes Persistent Volume Access Modes
  ##
  accessModes:
    - ReadWriteOnce
  ## @param persistence.size Size of data volume
  ##
  size: 8Gi
  ## @param persistence.existingClaim The name of an existing PVC to use for persistence
  ##
  existingClaim: ""
## @section Init Container Parameters
##

## 'volumePermissions' init container parameters
## Changes the owner and group of the persistent volume mount point to runAsUser:fsGroup values
##   based on the *podSecurityContext/*containerSecurityContext parameters
##
volumePermissions:
  ## @param volumePermissions.enabled Enable init container that changes the owner/group of the PV mount point to `runAsUser:fsGroup`
  ##
  enabled: false
  ## OS Shell + Utility image
  ## ref: https://hub.docker.com/r/bitnami/os-shell/tags/
  ## @param volumePermissions.image.registry OS Shell + Utility image registry
  ## @param volumePermissions.image.repository OS Shell + Utility image repository
  ## @param volumePermissions.image.tag OS Shell + Utility image tag (immutable tags are recommended)
  ## @param volumePermissions.image.pullPolicy OS Shell + Utility image pull policy
  ## @param volumePermissions.image.pullSecrets OS Shell + Utility image pull secrets
  ##
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: 11-debian-11-r%%IMAGE_REVISION%%
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
  ## Init container's resource requests and limits
  ## ref: http://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  ## @param volumePermissions.resourcesPreset Set init container resources according to one common preset (allowed values: none, nano, small, medium, large, xlarge, 2xlarge). This is ignored if volumePermissions.resources is set (volumePermissions.resources is recommended for production).
  ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  ##
  resourcesPreset: "nano"
  ## @param volumePermissions.resources Set init container requests and limits for different resources like CPU or memory (essential for production workloads)
  ## Example:
  ## resources:
  ##   requests:
  ##     cpu: 2
  ##     memory: 512Mi
  ##   limits:
  ##     cpu: 3
  ##     memory: 1024Mi
  ##
  resources: {}
  ## Init container Container Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param volumePermissions.containerSecurityContext.runAsUser Set init container's Security Context runAsUser
  ## NOTE: when runAsUser is set to special value "auto", init container will try to chown the
  ##   data folder to auto-determined user&group, using commands: `id -u`:`id -G | cut -d" " -f2`
  ##   "auto" is especially useful for OpenShift which has scc with dynamic user ids (and 0 is not allowed)
  ##
  containerSecurityContext:
    runAsUser: 0

## @section Other Parameters
##

## %%SUBCHART_CONTAINER/POD_DESCRIPTION%%
##
# %%SUBCHART_NAME%%:
SUBCHART_NAME:
  enabled: false
  # %%OTHER_PARAMETERS_RELATED_TO_THIS_SUBCHART%%
